before:
  hooks:
    - go generate ./...
project_name: syro
release:
  github:
    owner: danlemuelsalado
    name: syro-cli-charlie
builds:
  # amd64 builds
  - id: syro-cli-charlie-darwin-amd64
    ldflags:
      - -s -w -X github.com/danlemuelsalado/syro-cli-charlie/pkg/version.Version={{.Version}}
    binary: syro
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
  - id: syro-cli-charlie-linux-amd64
    ldflags:
      - -s -w -X github.com/danlemuelsalado/syro-cli-charlie/pkg/version.Version={{.Version}}
    binary: syro
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: syro-cli-charlie-windows-amd64
    ldflags:
      - -s -w -X github.com/danlemuelsalado/syro-cli-charlie/pkg/version.Version={{.Version}}
    binary: syro
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
  # arm64 builds
  - id: syro-cli-charlie-darwin-arm64
    ldflags:
      - -s -w -X github.com/danlemuelsalado/syro-cli-charlie/pkg/version.Version={{.Version}}
    binary: syro
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
  - id: syro-cli-charlie-linux-arm64
    ldflags:
      - -s -w -X github.com/danlemuelsalado/syro-cli-charlie/pkg/version.Version={{.Version}}
    binary: syro
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
  - id: syro-cli-charlie-windows-arm64
    ldflags:
      - -s -w -X github.com/danlemuelsalado/syro-cli-charlie/pkg/version.Version={{.Version}}
    binary: syro
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: "{{ .ProjectName }}checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"